owner: kontentsapp
repo: plotlab-status

sites:
  - name: AI Chat (Gemini)
    url: https://guosxfksrchplhbwzalx.supabase.co/functions/v1/ai-chat
    method: OPTIONS
    expectedStatusCodes: [200, 204]
    
  - name: AI Image (Imagen)
    url: https://guosxfksrchplhbwzalx.supabase.co/functions/v1/ai-image
    method: OPTIONS
    expectedStatusCodes: [200, 204]

  - name: AI Video (Veo)
    url: https://guosxfksrchplhbwzalx.supabase.co/functions/v1/ai-video
    method: OPTIONS
    expectedStatusCodes: [200, 204]

status-website:
  baseUrl: /plotlab-status
  name: PlotLab Status
  
workflowSchedule:
  uptime: "*/5 * * * *"
